# Generated by Django 5.2.4 on 2025-08-05 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteEssentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=255)),
                ('subheadline', models.CharField(blank=True, max_length=255)),
                ('cta', models.CharField(blank=True, max_length=255, verbose_name='Call to Action')),
            ],
        ),
    ]
