# Generated by Django 5.2.4 on 2026-05-13 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteessentials',
            name='address',
            field=models.TextField(blank=True, default='Glasgow, Scotland, United Kingdom'),
        ),
        migrations.AddField(
            model_name='siteessentials',
            name='company_name',
            field=models.CharField(default='M&M Recovery', max_length=120),
        ),
        migrations.AddField(
            model_name='siteessentials',
            name='default_google_map_embed',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='siteessentials',
            name='email',
            field=models.EmailField(blank=True, default='info@mandmrecovery.co.uk', max_length=254),
        ),
        migrations.AddField(
            model_name='siteessentials',
            name='opening_hours',
            field=models.TextField(blank=True, default='Mon-Sun: 12:00 AM - 11:59 PM'),
        ),
        migrations.AddField(
            model_name='siteessentials',
            name='phone_number',
            field=models.CharField(default='+447417425174', max_length=40),
        ),
        migrations.AddField(
            model_name='siteessentials',
            name='schema_image_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='siteessentials',
            name='schema_rating_value',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='siteessentials',
            name='schema_review_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, max_length=140)),
                ('location_type', models.CharField(choices=[('city', 'City'), ('area', 'Area')], default='area', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('meta_title', models.CharField(blank=True, max_length=255)),
                ('meta_description', models.TextField(blank=True)),
                ('google_map_embed', models.TextField(blank=True)),
                ('visit_title', models.CharField(blank=True, max_length=255)),
                ('visit_description', models.TextField(blank=True)),
                ('visit_address', models.TextField(blank=True)),
                ('visit_phone_number', models.CharField(blank=True, max_length=40)),
                ('visit_opening_hours', models.TextField(blank=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='mysite.location')),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('parent', 'slug'), name='unique_mandm_location_slug_per_parent')],
            },
        ),
    ]
