# Generated by Django 5.2.4 on 2026-05-13 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_siteessentials_address_siteessentials_company_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteessentials',
            name='address',
        ),
        migrations.RemoveField(
            model_name='siteessentials',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='siteessentials',
            name='default_google_map_embed',
        ),
        migrations.RemoveField(
            model_name='siteessentials',
            name='email',
        ),
        migrations.RemoveField(
            model_name='siteessentials',
            name='opening_hours',
        ),
        migrations.RemoveField(
            model_name='siteessentials',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='siteessentials',
            name='schema_image_url',
        ),
        migrations.RemoveField(
            model_name='siteessentials',
            name='schema_rating_value',
        ),
        migrations.RemoveField(
            model_name='siteessentials',
            name='schema_review_count',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
