# Generated by Codex on 2026-05-14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mysite", "0003_remove_siteessentials_address_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=120)),
                ("slug", models.SlugField(blank=True, max_length=140)),
                ("location_type", models.CharField(choices=[("city", "City"), ("area", "Area")], default="area", max_length=20)),
                ("is_active", models.BooleanField(default=True)),
                ("is_featured", models.BooleanField(default=False)),
                ("meta_title", models.CharField(blank=True, max_length=255)),
                ("meta_description", models.TextField(blank=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="mysite.location",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddConstraint(
            model_name="location",
            constraint=models.UniqueConstraint(fields=("parent", "slug"), name="unique_mandm_location_slug_per_parent"),
        ),
        migrations.AddIndex(
            model_name="location",
            index=models.Index(fields=["parent", "slug"], name="mysite_loca_parent__fc397b_idx"),
        ),
        migrations.AddIndex(
            model_name="location",
            index=models.Index(fields=["is_active", "is_featured"], name="mysite_loca_is_acti_0e9213_idx"),
        ),
    ]
