# Generated by Django 5.2.4 on 2025-08-07 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleReview',
            fields=[
                ('review_id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('author', models.CharField(blank=True, max_length=255, null=True)),
                ('profile_picture', models.URLField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('body', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
